language: node_js
node_js:
- 12.4.0
cache:
  directories:
  - node_modules
dist: trusty
install:
- npm install
script:
- npm run build
notifications:
  email:
  - ebrehault@gmail.com
jobs:
  include:
    - stage: Tagging
      if: (branch = master) AND (tag IS blank)
      after_success: source ./deploy.sh
      deploy:
        provider: releases
        api_key:
          secure: AnWeTpX9vC/IBw+JayoZHhfm6vUine28cg+R1E/6tIvhoNwbmQk6WWmWX/SLei6db8KVzpexh1mShvo9xcv+FWOYz5ms2y7YB3E4BPVP6+lBPmFByjGj6lLfR/jhIAfG1DFiffdE5PBVyrknKCD2Y8+gh56wr0oiSE6g9xdJRZilpg3qPzez1x0r802A87Jd3cZIdQEzLGyaCGTm9POdoLcGsnjL4SAi0cqAvcNiziMwybSyU884uBX/sYjrxMwGsbN23CBD8KWMysNsJO8eSSRlASRlPq+5iBNyCndsjzRgVfZy1HUKljXiIrZNcjlA4vVQP9BieHkAn+6WununLMlUJBRdb4s59vaISpf8ACVg8SLIkiIkj8I4Rajob46A3s4eRmfJpkQuYe+tJFyCvXntU88isBoJGn9QoKjaP27RyTBtmxkmzKwlkjNAWsLEXSJxCJrDKMAcBuYbg0UKEkZKyPDgz6fwkW9RsMnXiuawY5xFTjicU39/LDwcWmP8c5sVw6aOaqQ91qf0YF6KxyKH8IzmxBS8coGq2gvat4g4rAh9UWkZbLeJhIIuH/jAr0WhpWOjswRJk0igKuZfxZS0XhTvJIjE1x+26XXU3cwL2cxTbZKpbOwfZvTik9+8QPrW9OBelrUAuJaiUC3EXxPN4SyiJ4jChMdptWdoiyI=
        name: Build $PACKAGE_VERSION
        on:
          repo: guillotinaweb/grange
          branch: master
          tags: true
    - stage: NPM release
      if: tag IS present
      before_deploy: cd dist/grange
      deploy:
        provider: npm
        edge: true
        email: ebrehault@gmail.com
        skip_cleanup: true
        api_key:
          secure: N1c+fdMKX3YLTSTXM1zJ0JDojugB6qAx+fcq9IBS07iF34jJni0oal8XiR207a6NKyr018tQFhgOUEeuS/dbcx6cWWNFWahiFSISakFunlq6vGYJd2oHDkyHJZinKPI53oJc1UP8CqL0juXak2oyN/SXD6GZZ79XRQ2CYg6Es4tdPOyVBS+e4DGViJbGgcrbnvD4LA3KQbGzp79CGhu2JvHS4UsNq73B4Y8tp4hC2UMRwBp5nr2zEmyCPLSiqdBPJZyn5mMLIWOJoGeKDuZ3UF9o+V2xypg5WQpORWyHwi0VTUTLOt79VRwz8XUKZXYxsw6SkjFQmVGDk2XWGm/Uz17BlCaI/3zYONMO6nf6U8HpYqk5hfjNC+bxSuuW/HabzcUa3qMA//X5HZ/eG/e/WCFs830gkRvZmHVdr7pEA9cvBzoG2CnkX6nyL1VpkUrtrYMlpmA48vWXNC8Mea83fNRihqEVa9McBAoQYPto1kClgka0olOl66WCuIH2wK7IBG7o6UMrFhGQQIwKngtcFsxJjlAJigiyTE83fzfYVu4AJHV3IMCLFQllSa38jc8PAV9HzqjDDzf3Recrj0VzvxPo+lWc9/JJtOPYJrOTHBPe0nThiY05uD9tdV9nu8mhwA7Wl9Z6iqi0Fo/zZ8d7U1awBPAMPMcW7JXDhacOXmk=
        on:
          tags: true
          repo: guillotinaweb/grange
          branch: master

